extends: eslint:recommended
env:
  node: true
  browser: true
  commonjs: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module

rules:
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
